name: Create data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full
          pip install jupyter nbconvert
          pip install pandas
          pip install requests
          pip install pyunpack patool

      - name: Run notebooks
        run: |
          jupyter nbconvert --to notebook --execute create_data.ipynb
          
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'data.csv'
          commit_message: 'Create data.csv'
          skip_dirty_check: false
